### ISSUE TITLE
Matching against opt-in list is case-sensitive

### ISSUE THREAD

**Issue by JamesMGreene** [lerebear/sizeup-action#51]
Thanks for this cool action! ▶️ 💝 

The current matching technique used to determine if a user is opted in to SizeUp is case-sensitive:

https://github.com/lerebear/sizeup-action/blob/cb3a93a2d6c0c5983116f345086b8606863dbc60/src/initializer.ts#L43-L46

This means that if the configuration file casing does not match their official GitHub username casing, it will consider the user opted out instead.

As least within GitHub, most of our configurations are intentionally case-insensitive for similar "gotcha" reasons. It would be great if this action could be updated to allow for that as well. ❤ 

I'm imagining the needed code change is roughly as easy as settling on a consistent casing for both sides of the comparison, e.g.

```ts
  const pullAuthor = pull.user.login.toLowerCase()
  const usersWhoHaveOptedin = config.optIns || []
  const userHasOptedOut =
    usersWhoHaveOptedin.length &&
    !usersWhoHaveOptedin.find((login: string) => login.toLowerCase() === pullAuthor)
```

Alternatively, you could use something like [`String#localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare), though the many input options for that are a bit cumbersome IMHO.

Would also be ideal to add a test for this case-insensitivity to prevent later regression. 🧪

**Comment by lerebear** [comment]
Thank you for the report @JamesMGreene!

> I'm imagining the needed code change is roughly as easy as settling on a consistent casing for both sides of the comparison

Yes, I agree that this should be sufficient.
